{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPSetupIntentLastSetupErrorType"]]},"metadata":{"roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPSetupIntentLastSetupErrorType@STPSetupIntentLastSetupErrorTypeAPIConnection","title":"STPSetupIntentLastSetupErrorType.apiConnection","role":"symbol","modules":[{"name":"Stripe"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apiConnection"}]},"abstract":[{"type":"text","text":"An error connecting to Stripe’s API."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPSetupIntentLastSetupErrorType\/apiConnection","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(STPSetupIntentLastSetupErrorTypeAPIConnection) ","kind":"text"},{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apiConnection"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpsetupintentlastsetuperrortype\/apiconnection"]}],"kind":"symbol","sections":[],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","title":"Stripe","type":"topic","role":"collection","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPSetupIntentLastSetupErrorType":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPSetupIntentLastSetupErrorType","type":"topic","title":"STPSetupIntentLastSetupErrorType","navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"abstract":[{"type":"text","text":"The type of the error represented by "},{"type":"codeVoice","code":"STPSetupIntentLastSetupError"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Some STPSetupIntentLastError properties are only populated for certain error types.","type":"text"}],"url":"\/documentation\/stripe\/stpsetupintentlastsetuperrortype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPSetupIntentLastSetupErrorType/apiConnection":{"type":"topic","url":"\/documentation\/stripe\/stpsetupintentlastsetuperrortype\/apiconnection","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apiConnection"}],"title":"STPSetupIntentLastSetupErrorType.apiConnection","abstract":[{"type":"text","text":"An error connecting to Stripe’s API."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPSetupIntentLastSetupErrorType\/apiConnection"}}}